micronaut:
  application:
    name: paky
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:57655/test`}
    username: ${JDBC_USER:test}
    password: ${JDBC_PASSWORD:test}
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
